apiVersion: v2
name: shenyu
description: Helm Chart for deploying Apache ShenYu in Kubernetes
type: application
version: 0.1.0
appVersion: "2.4.3"
icon: https://shenyu.apache.org/img/logo.png
maintainers:
  - name: erdengk
  - name: aFlyBird0
    email: aflybird0@gmail.com
