apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{.Release.Namespace}}
  name: {{ template "shenyu.fullname" . }}-configmap
  labels:
    "app.kubernetes.io/name": '{{ template "shenyu.name" . }}'
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/component": "shenyu-configmap"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
data:
  application-local.yml: |
    server:
      port: 9195
      address: 0.0.0.0
    spring:
      profiles:
        active: {{ .Values.dataSource.active }}
      main:
        allow-bean-definition-overriding: true
      application:
        name: shenyu-bootstrap
    management:
      health:
        defaults:
        enabled: false
    shenyu:
      local:
        enabled: true
      file:
        enabled: true
      cross:
        enabled: true
      dubbo:
        parameter: multi
      sync:
        websocket:
          urls: ws://{{ template "shenyu.fullname" . }}-admin.shenyu.svc.cluster.local:9095/websocket
      exclude:
        enabled: false
        paths:
        - /favicon.ico
      extPlugin:
        enabled: true
        threads: 1
        scheduleTime: 300
        scheduleDelay: 30
      scheduler:
        enabled: false
        type: fixed
        threads: 16
    logging:
      level:
        root: info
        org.springframework.boot: info
        org.apache.ibatis: info
        org.apache.shenyu.bonuspoint: info
        org.apache.shenyu.lottery: info
        org.apache.shenyu: info
  {{- if eq .Values.dataSource.active "h2" }}
  application-h2.yml: |
    shenyu:
      database:
        dialect: h2
        init_script: "sql-script/h2/schema.sql"
        init_enable: {{ .Values.dataSource.initEnabled }}
    spring:
      datasource:
        url: jdbc:h2:mem:~/shenyu;DB_CLOSE_DELAY=-1;MODE=MySQL;
        username: {{ .Values.dataSource.h2.username }}
        password: {{ .Values.dataSource.h2.password }}
        driver-class-name: org.h2.Driver
  {{- end }}
  {{- if eq .Values.dataSource.active "mysql" }}
  application-mysql.yml: |
    shenyu:
      database:
        dialect: mysql
        init_enable: {{ .Values.dataSource.initEnabled }}
    spring:
      datasource:
        url: jdbc:mysql://{{ template "shenyu.fullname" . }}-mysql.shenyu.svc.cluster.local:3306/shenyu?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: {{ .Values.dataSource.mysql.username }}
        password: {{ .Values.dataSource.mysql.password }}
        driver-class-name: {{ .Values.dataSource.mysql.driverClass }}
  {{- end }}
