{{- if .Values.admin.ingress.enabled -}}
{{- $fullName := include "common.names.fullname" . -}}
{{- $ingressPath := .Values.admin.ingress.path -}}
{{- $servicePort := .Values.admin.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: '{{ $fullName }}-admin'
  labels:
    "app.kubernetes.io/name": '{{ template "common.names.name" . }}-admin'
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/component": "shenyu-admin"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
{{- with .Values.admin.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.admin.ingress.tls }}
  tls:
  {{- range .Values.admin.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.admin.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
  {{- end }}
{{- end }}