{{- if .Values.admin.enabled -}}
# Now we only support NodePort mode
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "shenyu.fullname" . }}-admin
  labels:
    "app.kubernetes.io/name": '{{ template "shenyu.name" . }}-admin'
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/component": "shenyu-admin"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
spec:
  selector:
    "app.kubernetes.io/component": "shenyu-admin"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
  type: NodePort
  ports:
    - protocol: TCP
      port: 9095
      targetPort: 9095
      nodePort: {{ .Values.admin.nodePort }}
{{- end -}}
