{{- if .Values.admin.enabled -}}
{{- if eq .Values.dataSource.active "mysql" -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "shenyu.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ required ".Values.dataSource.mysql.storageClass is required" .Values.dataSource.mysql.storageClass}}
---
{{- end -}}
{{- end -}}
